// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb-sSWpJPSQUChw_qndxQhJOP3Nx5nTbE',
    appId: '1:996118329348:web:518dbf905db31755e79d51',
    messagingSenderId: '996118329348',
    projectId: 'aerion-super-apps',
    authDomain: 'aerion-super-apps.firebaseapp.com',
    storageBucket: 'aerion-super-apps.firebasestorage.app',
    measurementId: 'G-15J055276K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJKHqh1wlB-1PznYWCNuDWRl8BarsfBhM',
    appId: '1:996118329348:android:aa898d80d3bcf88ce79d51',
    messagingSenderId: '996118329348',
    projectId: 'aerion-super-apps',
    storageBucket: 'aerion-super-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlasDUPKaLa-FPgkbYAMDpP-NYPXJSB78',
    appId: '1:996118329348:ios:f770bcda73140927e79d51',
    messagingSenderId: '996118329348',
    projectId: 'aerion-super-apps',
    storageBucket: 'aerion-super-apps.firebasestorage.app',
    iosBundleId: 'com.aerion',
  );
}
