// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ADGXrTIT1lSZOwshuiKiKhgEP5bZjAY',
    appId: '1:365053340453:web:eea83afd03d5da097248cc',
    messagingSenderId: '365053340453',
    projectId: 'aerion-dashboard-26510',
    authDomain: 'aerion-dashboard-26510.firebaseapp.com',
    storageBucket: 'aerion-dashboard-26510.firebasestorage.app',
    measurementId: 'G-C3LPCFT8PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATso9g69bC9y1sjBbXgDMKuR31ZFOCwcw',
    appId: '1:365053340453:android:cd87c67d203d30427248cc',
    messagingSenderId: '365053340453',
    projectId: 'aerion-dashboard-26510',
    storageBucket: 'aerion-dashboard-26510.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGvlfgMlLAYcRKxVAu6I0nZLmqihOXVmY',
    appId: '1:365053340453:ios:37bd4d8863a5676d7248cc',
    messagingSenderId: '365053340453',
    projectId: 'aerion-dashboard-26510',
    storageBucket: 'aerion-dashboard-26510.firebasestorage.app',
    iosBundleId: 'com.aerion',
  );
}
